### PR TITLE
Added a way to specify where asteroids land via dimension IDs | FEAR THE POWER OF THE SKY

### PR DESCRIPTION
**Pull request by SebaSphere**
Fixed some spelling mistakes and added some javadocs too
This should theoretically work. Tested a bit and seems fine.

### CODE REVIEW

**Comment by SebaSphere** [comment]
It works btw. Doesn't seem to spawn any asteroids in dimensions without config specified like Kepler 22b

**Comment by ROMVoid95** [comment]
The problem with this is each addon specifies 2 properties in each of their planets WorldProvider classes with this overriding method

```java
@Override
public double getMeteorFrequency () {
	return <amount>;
}
```

1. If meteors spawn in the planets dimension, 0 = No spawn
2. If they do then what is the spawn rate

With the changes made your essentially overriding the addons set amount. The other issue is that your not actually overriding anything and if a dimension is set to spawn in, then it will just add even more meteor spawns.

**Comment by SebaSphere** [comment]
Yeah there probably needs to be a disclaimer that u needa disable asteroids in other add-ons / gc config for problem number 2. Saw that being a potential problem but didn't think too much for a disclaimer

Spawn rate being increased is probably what happens since code just spawns a asteroid.

What addons use "getMeteorFrequency" tho out of curiosity and what?

**Comment by ROMVoid95** [comment]
all of them

**Comment by SebaSphere** [comment]
Well my code works lol

**Comment by SebaSphere** [comment]
closing PR since pushing commits as apart of a new one

**Pull request closed without merging**
